./LQSkimmer ../ROOT/LQSignals/lq1000.root    0
./LQSkimmer ../ROOT/LQSignals/lq1050.root    0
./LQSkimmer ../ROOT/LQSignals/lq1100.root    0
./LQSkimmer ../ROOT/LQSignals/lq1150.root    0
./LQSkimmer ../ROOT/LQSignals/lq1200.root    0
./LQSkimmer ../ROOT/LQSignals/lq1250.root    0
./LQSkimmer ../ROOT/LQSignals/lq1300.root    0
./LQSkimmer ../ROOT/LQSignals/lq1350.root    0
./LQSkimmer ../ROOT/LQSignals/lq1400.root    0
./LQSkimmer ../ROOT/LQSignals/lq1450.root    0
./LQSkimmer ../ROOT/LQSignals/lq1500.root    0
./LQSkimmer ../ROOT/LQSignals/lq200.root    0
./LQSkimmer ../ROOT/LQSignals/lq250.root    0
./LQSkimmer ../ROOT/LQSignals/lq300.root    0
./LQSkimmer ../ROOT/LQSignals/lq350.root    0
./LQSkimmer ../ROOT/LQSignals/lq400.root    0
./LQSkimmer ../ROOT/LQSignals/lq450.root    0
./LQSkimmer ../ROOT/LQSignals/lq500.root    0
./LQSkimmer ../ROOT/LQSignals/lq550.root    0
./LQSkimmer ../ROOT/LQSignals/lq600.root    0
./LQSkimmer ../ROOT/LQSignals/lq650.root    0
./LQSkimmer ../ROOT/LQSignals/lq700.root    0
./LQSkimmer ../ROOT/LQSignals/lq750.root    0
./LQSkimmer ../ROOT/LQSignals/lq800.root    0
./LQSkimmer ../ROOT/LQSignals/lq850.root    0
./LQSkimmer ../ROOT/LQSignals/lq900.root    0
./LQSkimmer ../ROOT/LQSignals/lq950.root    0
